### ISSUE TITLE
Payment issue?

### ISSUE THREAD

**Issue by peteruithoven** [mdh34/quickDocs#13]
Thanks for creating this app, I'd love more convenient access to Devdocs. 

I was trying to pay for this app but I ran into the following error: 

> There was a problem processing your payment
> An error occurred while processing the card. Please try again later. We apologize for any inconvenience caused.

Which seems the same as the payment issue I was having with Quilter: https://github.com/lainsce/quilter/issues/76
Have you received other payments? 

Looking at my creditcard payments, the amount does seem to be "Reserved".

**Comment by mdh34** [comment]
@peteruithoven I'm contacting the appcenter Devs to see what's up. thank you for buying the app!😊

**Comment by btkostner** [comment]
What country is your card from, and what type of card is it (Visa, MasterCard, etc) @perteruithoven?

What country is your Stipe account from @mdh34?

**Comment by mdh34** [comment]
@btkostner uk

**Comment by peteruithoven** [comment]
@btkostner My card is from the Netherlands (dutch). It's a Mastercard.

**Comment by btkostner** [comment]
From what I can put together from the logs. It seems @mdh34 recently updated / switched the Stripe account connected to the app, and AppCenter on @peteruithoven's computer was still trying to use the old stripe account. This caused a `400 Bad Request` error because of the mismatch.

**Comment by mdh34** [comment]
@btkostner makes sense, I was fiddling with stripe earlier

**Comment by peteruithoven** [comment]
Lol, now we have two possible issues or they where both in effect? 

@btkostner When is that updated? Is that updated when the repositories are updated (`apt update` like)? 

@mdh34 you think your verification issue was the main reason? 

I'll try again anyway.

**Comment by mdh34** [comment]
@peteruithoven should be, that was the reason for the error in the logs

**Comment by peteruithoven** [comment]
Alright, I've tried it again after running some updates. Now I'm getting the following error:

> There was a problem processing your payment
> Please review your payment info and try again.

Which seems like I filled in something wrong, but I've double checked and retyped everything. I also now seem to have two reservations for this purchase in my creditcard payment log. I've also purchased other apps in the past. You guys now see other logs?

**Comment by btkostner** [comment]
Yes, the appstream information is updated with `apt update`. You might also want to try doing `sudo appstreamcli refresh-cache --force` to be extra safe.

I also opened a PR in houston that should hopefully improve the error rates for things like this.

**Comment by mdh34** [comment]
Ok, so looking at the stripe logs there are some more token requests from @peteruithoven there, but they're all returning "200 OK"

**Comment by mdh34** [comment]
![_20180110_223758](https://user-images.githubusercontent.com/12615975/34799401-95ca8b14-f657-11e7-9ab4-fb1aec0a5010.JPG)

**Comment by btkostner** [comment]
Looking at the api it seems the application key that is given is not the correct one, and that is where the error is occuring. The PR I submitted should fix that.

**Comment by mdh34** [comment]
@btkostner the API key in the request doesn't match my key so hopefully that should fix it :)

**Comment by mdh34** [comment]
@btkostner what about the reservations on @peteruithoven 's card - will they go away?

**Comment by btkostner** [comment]
They are just reservations. Because the charge never went through they should go away. Depends how fast your bank is. For mine it usually takes a day or two.

**Comment by btkostner** [comment]
I just merged and deployed an update to houston. If you try now it _should_ work.

**Comment by peteruithoven** [comment]
I did a `apt update` and `sudo appstreamcli refresh-cache --force` and success! Although it will likely be the fixes you guys did that did the trick. 
I'm glad we've been able to figure this out.

**Comment by mdh34** [comment]
Glad this is sorted 😊 thanks @btkostner for your help and @peteruithoven for your patience!
