### ISSUE TITLE
Download docs locally

### ISSUE THREAD

**Issue by Alecaddd** [mdh34/quickDocs#14]
A great little app, really useful to avoid keeping a browser tab always open.
I was wondering if you were already considering adding the ability to download locally the entire docs website, or maybe a portion of it, to browse it locally.
Thanks

**Comment by mdh34** [comment]
The devdocs portion of the app supports offline/local downloads if you go into the menu. At the moment I haven't implemented anything for local valadoc but I'll take a look :)

**Comment by cassidyjames** [comment]
That would be awesome and really sell me on this app versus a browser tab!

**Comment by mdh34** [comment]
kind of stuck on how to implement this: the only offline valadoc implementation i can find uses devhelp, and the only vala bindings i can find for libdevhelp are ~7 years old

**Comment by mdh34** [comment]
Added this in 1.2.0 :)
