### ISSUE TITLE
Remember tab?

### ISSUE THREAD

**Issue by peteruithoven** [mdh34/quickDocs#15]
I would love it if quickDocs could remember the tab/page it was on last time and restore that when re-opened. 
For users that mostly use devdocs that would save a mouse action on every open. (Is there a keyboard shortcut to switch tabs/pages?)

**Comment by mdh34** [comment]
Fixed! If I added a keyboard shorcut, what would be a good combination?

**Comment by peteruithoven** [comment]
Awesome, that was quick! 
Not sure, it's hard to come up with something that can't conflict with the web pages and is intuitive. 
Maybe the keyboard shortcuts that are normally used for switching tabs? Like:
- <kbd>ctrl</kbd>+<kbd>tab</kbd> / <kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>tab</kbd>
- <kbd>alt</kbd>+<kbd>1</kbd> / <kbd>alt</kbd>+<kbd>2</kbd>

**Comment by mdh34** [comment]
@peteruithoven added <kbd>ctrl</kbd>+<kbd>tab</kbd> now!
