### ISSUE TITLE
Theme switcher button is unclear.

### ISSUE THREAD

**Issue by TraumaD** [mdh34/quickDocs#19]
The weather icon for changing theme is a little unclear. I think using the object-inverse icon would make more sense. I've seen other projects use it for this purpose in the past. If you need the icon to be symbolic I just added a symbolic version to the elemenatry icon set but it's not available yet.

object-inverse: ![object-inverse](https://user-images.githubusercontent.com/10608836/35028064-aeecd504-fb19-11e7-9b04-7551cd216730.png)

object-inverse-symbolic: ![object-inverse-symbolic](https://user-images.githubusercontent.com/10608836/35028129-f94ce0e4-fb19-11e7-958d-fac3fc35cfbf.png)

**Comment by mdh34** [comment]
I agree, it's a lot clearer as to what the button does
