### ISSUE TITLE
could you make a flatpak for quickDocs?

### ISSUE THREAD

**Issue by altntowin** [mdh34/quickDocs#22]
Hi, I really appreciate your work , is a good application
but i don't use elementary OS
could you make a flatpak for quickDocs?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by mdh34** [comment]
At the moment I don't have the time or know-how to make a flatpak for quickDocs, but i'm totally open to anyone in the community wanting to help out.

Have you tried installing from source?
