### ISSUE TITLE
Remove extra dependencies

### ISSUE THREAD

**Issue by tintou** [mdh34/quickDocs#30]
https://github.com/mdh34/quickDocs/blob/4c450df2cc34fafaf0c7d3a5b4484c8754985790/debian/control#L16
${misc:Depends}, ${shlibs:Depends} are enough, the dependencies are calculated automatically, plus you don't need curl or wget now that you're using native functions

**Comment by mdh34** [comment]
Fixed! Thanks for the feedback :)
