### ISSUE TITLE
DevDocs does not work offline

### ISSUE THREAD

**Issue by ayoisaiah** [mdh34/quickDocs#31]
It always shows this error when I open the app without an active connection. This happens even though I have downloaded some documentation for offline use

![screenshot from 2018-04-15 18 59 42](https://user-images.githubusercontent.com/13372163/38781610-a6c5ce7e-40df-11e8-940a-bc0eb87d59b9.png)

**Comment by mdh34** [comment]
This should be fixed as of https://github.com/mdh34/quickDocs/commit/1cad4e79e2cd9672de047059af3c9eaa966d46d3, let me know if this works with the latest release (you'll need to toggle the theme back and forth once while you're online to refresh the cache)
