### ISSUE TITLE
Missing Icon when building from source

### ISSUE THREAD

**Issue by MichaelAquilina** [mdh34/quickDocs#32]
![screenshot from 2018-04-24 10-45-37](https://user-images.githubusercontent.com/2650040/39179684-c5184810-47ac-11e8-8dc2-7263c75c60b4.png)

(See top right corner)

Built from source on OpenSUSE Tumbleweed following the instructions on the README.

Let me know if there are any other details I can provide to help figure out what the issue is.

**Comment by mdh34** [comment]
It looks like your icon theme is missing the object-inverse icon. Out of interest, are any of the download icons on the vala tab missing as well?

**Comment by MichaelAquilina** [comment]
yeah they seem to have the exact same issue:

![screenshot from 2018-04-24 11-14-16](https://user-images.githubusercontent.com/2650040/39181177-c491813c-47b0-11e8-9c9f-62749062e83f.png)

**Comment by MichaelAquilina** [comment]
The Icon theme I have enabled is the default "Adwaita" icon theme that comes with SUSE and I think most gnome distros
![screenshot from 2018-04-24 11-15-18](https://user-images.githubusercontent.com/2650040/39181228-e93df09c-47b0-11e8-8335-aeb733531195.png)

**Comment by mdh34** [comment]
This should now be fixed in master, let me know if you have any more issues :)

**Comment by MichaelAquilina** [comment]
Testing it now!
