### ISSUE TITLE
no menu DevDocs

### ISSUE THREAD

**Issue by DexterMorgan62** [mdh34/quickDocs#42]
Hello,

I can not go back to access the different documents in DevDocs.
I'm stuck on the CSS-TRICKS page and I have no menu left!
I have uninstalled and reinstalled and still the same page.
I have the latest version 2.0.4. I had the same problem with the old version.
I am under elementary 0.4.1 loki on zenbook UX305FA.
How to completely erase application and reinstall?

Thank you for this application and your help.

![capture d ecran de 2018-06-12 13-59-41](https://user-images.githubusercontent.com/8545093/41289823-4b932436-6e4b-11e8-9d9e-7c536edf6739.png)
![capture d ecran du 2018-06-12 14 00 37](https://user-images.githubusercontent.com/8545093/41289942-9e2e8c1c-6e4b-11e8-8b7e-8d65638e9e57.png)
![capture d ecran du 2018-06-12 14 00 50](https://user-images.githubusercontent.com/8545093/41289955-a5017c52-6e4b-11e8-80eb-3c0a4216dc22.png)

**Comment by mdh34** [comment]
if you run 
`dconf reset /com/github/mdh34/quickdocs/last-dev`
in terminal while the application is closed and relaunch the application it should reset the page back to default

I'll implement something in the next release to make this easier

**Comment by DexterMorgan62** [comment]
The reset worked
thank you very much

**Comment by mdh34** [comment]
Fixed
