### ISSUE TITLE
 Enable a search engine

### ISSUE THREAD

**Issue by alainm23** [mdh34/quickDocs#49]
Before thank you for developing this incredible application.
In ValaDoc the list of documentation is very long, a search engine would make the search easier

**Comment by mdh34** [comment]
are you referring to the list of packages? If so this was added in https://github.com/mdh34/quickDocs/commit/6122daf8095d97b2e661d172160043273817d74a and should be present in the 2.1.1 release

**Comment by alainm23** [comment]
Thank you very much, I did not realize :100:
