### ISSUE TITLE
Download all valadoc packages

### ISSUE THREAD

**Issue by ethchest** [mdh34/quickDocs#50]
I would like to download all valadocs at once. Often, I do not know in advance which docs I will need, and it takes a while to click everything separately.

Of course, you can just click everything manually, but it would be much nicer this way imo.

**Comment by mdh34** [comment]
The DevDocs side of things has an 'Install all' button on the offline settings page. I can however add a button for the valadoc offline packages.

**Comment by ethchest** [comment]
Thanks, that would be great. I couldn't really get Devdocs to work reliably, it's always glitchy/doesn't show up or only late. This is with flatpak because if I remember correctly on Xenial I had some trouble with some of the dependencies.
Sometimes I also get `Error performing TLS handshake: An unexpected TLS packet was received.` but I can also put that into a separate issue.

**Comment by mdh34** [comment]
This has been started in the `dev` branch now (see https://github.com/mdh34/quickDocs/commit/1c73c260b40d8ae32b76044486f40b0c78c57ea4)

I've experienced the TLS error with my other app as well and I'm not entirely sure where it comes from, unfortunately the network stack doesn't automatically reattempt connections so things can drop out - I'll take a look to see if I can reproduce and work around it.

See #37 for the DevDocs issue

**Comment by ethchest** [comment]
Thanks, nice to know. Yeah, I am following #37 but that did not give any insight. Sometimes right clicking seems to help. I might work on implementing valadocs in doc2dash, then you could just use devdocs.

**Comment by ethchest** [comment]
@mdh34 One question about valadoc - when looking into how to turn it into a docset, I noticed that there doesn't seem to be a just a tarball or so of all the docs. Do you know about something like that? I really do not want to generate all the docs for all the packages by hand and it seems the valadoc people do not like people to scrape valadoc.org (there is a mailinglist thread about it) It probably would still work with something like scrapy, but not sure how long it would take me.

**Comment by mdh34** [comment]
There's a set of .tar.xz packages that quickDocs and the gnome devhelp program use available on the valadoc page that seem similar to the dash style of packaging - I'd take a look at Services/Download.vala in this repo and https://notabug.org/grindhold/my_valadoc/src/master/my_valadoc.sh

**Comment by ethchest** [comment]
Ah yeah, I saw those now while downloading. I thought quickdocs just displays the webpage? Or does it use the .tar.xz packages for offline mode? Thanks for the links.

**Comment by mdh34** [comment]
No, quickDocs uses libdevhelp to parse the package directories in offline mofe

**Comment by mdh34** [comment]
This is finished and now part of `2.2.0`, the flatpak is up and it's just been submitted to appcenter
