### ISSUE TITLE
Screenshots have incorrectly rendered borders

### ISSUE THREAD

**Issue by danrabbit** [mdh34/quickDocs#52]
I've marked the latest release of quickDocs as "Needs Fixing" beause the screenshots have incorrectly rendered borders. You can see [thick black lines](https://raw.githubusercontent.com/mdh34/quickDocs/6ba08fce989ba9cbdb18698ed779ba40e9874a12/data/images/screenshot-3.png) around the window instead of the intended shadows.

You can get transparent screenshots with shadows using the built-in screenshot tool and selecting "Grab the current window"

**Comment by mdh34** [comment]
Fixed as of 2.2.1
