### ISSUE TITLE
Unable to download more then 2 offline doc

### ISSUE THREAD

**Issue by moxou** [mdh34/quickDocs#58]
**Describe the bug
I try to download documentation for offline use, unfortunatly after having download 2 library when I try to download a 3rd one, ValaDoc crash
**To Reproduce**
Trying to download more than 2 library doc

**Expected behavior**
valaDoc close without warning or log

**Screenshots**

**System Information**
 - Distribution: elementary OS 5.0 Juno
 - Desktop Environment: [GNOME]
 - Installation Method: ]

**Comment by mdh34** [comment]
Fixed as of latest release
