### ISSUE TITLE
can not install flatpak

### ISSUE THREAD

**Issue by eexpress** [mdh34/quickDocs#62]
**Describe the bug**
when install....
```
▶ sudo flatpak install flathub com.github.mdh34.quickdocs
Looking for matches…
error: No remote refs found similar to ‘flathub’
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**System Information**
 - Distribution: 
 - Desktop Environment: [GNOME. KDE, Pantheon, etc.]
 - Installation Method: [Debian Package, AUR, Flatpak, from source etc.]

**Comment by mdh34** [comment]
This error message probably means you don’t have the flathub remote setup and isn’t a quickdocs bug - try running ```flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo ```and try again
