### ISSUE TITLE
Background is dark and and text is unclear

### ISSUE THREAD

**Issue by rasmus91** [mdh34/quickDocs#66]
The background has gone dark making text incredibly difficult to read.

install the app and look at the Vala documentation

If the background is to be dark the text should be light so there is proper contrast and everything is clear to read.

![Skærmbillede fra 2019-11-12 11-30-50](https://user-images.githubusercontent.com/2297739/68664092-0f3e2c00-0540-11ea-8622-7d35ded6c039.png)

**System Information**
 - Distribution: elementary OS Juno
 - Desktop Environment:Pantheon
 - Installation Method: elementary OS AppCenter

**Comment by phase1geo** [comment]
I am seeing this same issue as well.

**Comment by mdh34** [comment]
Hi, just checking in on this! I'm unable to reproduce this on a fresh install, please let me know if this is still an issue.

**Comment by rasmus91** [comment]
This is no longer a problem. I suspect it was something with the Webkit engine or some such, attempting to do a dark mode, maybe?

Anyhow, one day I opened it again after not having used it for weeks, and it seemed fine again.
